name: Kulwinder - Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    
    permissions:
      contents: read
      issues: write

    steps:
    - uses: actions/checkout@v4

    - name: Run a one-line script
      run: echo "Hi, I am from COSC 1209 class"
        
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle Wrapper
      run: ./gradlew build

    - name: Build Docker image
      run: docker build -t java-app .

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Tag Docker image
      run: docker tag java-app ${{ secrets.DOCKERHUB_USERNAME }}/demo-app:java-1.0

    - name: Push Docker image
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/demo-app:java-1.0
